# Generated by Django 5.2.13 on 2026-04-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employee_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
