# Generated by Django 5.2.13 on 2026-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staffprofile_can_manage_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="cannot_work_night",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="is_new_mother",
            field=models.BooleanField(default=False),
        ),
    ]
