from django.urls import path

from .views import (
    AvailabilityRequestDetailView,
    AvailabilityRequestListCreateView,
    AvailabilityRequestReviewView,
    AnalyticsReportView,
    AssignmentTemplateExportView,
    AutoScheduleCommitView,
    AutoSchedulePreviewView,
    CalendarEventsView,
    DashboardSummaryView,
    LegacyAssignmentBulkActionView,
    MoveAssignmentView,
    ShiftTypeDetailView,
    ShiftTypeListCreateView,
    StaffScheduleEventsView,
    StaffAvailabilityDetailView,
    StaffAvailabilityListCreateView,
    UnitRequirementDetailView,
    UnitRequirementListCreateView,
    WorkAssignmentDetailView,
    WorkAssignmentListCreateView,
)

urlpatterns = [
    path("shift-types/", ShiftTypeListCreateView.as_view(), name="shift-type-list"),
    path("shift-types/<int:pk>/", ShiftTypeDetailView.as_view(), name="shift-type-detail"),
    path(
        "unit-requirements/",
        UnitRequirementListCreateView.as_view(),
        name="unit-requirement-list",
    ),
    path(
        "unit-requirements/<int:pk>/",
        UnitRequirementDetailView.as_view(),
        name="unit-requirement-detail",
    ),
    path("assignments/", WorkAssignmentListCreateView.as_view(), name="assignment-list"),
    path("assignments/<int:pk>/", WorkAssignmentDetailView.as_view(), name="assignment-detail"),
    path("availability/", StaffAvailabilityListCreateView.as_view(), name="availability-list"),
    path(
        "availability/<int:pk>/",
        StaffAvailabilityDetailView.as_view(),
        name="availability-detail",
    ),
    path(
        "availability-requests/",
        AvailabilityRequestListCreateView.as_view(),
        name="availability-request-list",
    ),
    path(
        "availability-requests/<int:pk>/",
        AvailabilityRequestDetailView.as_view(),
        name="availability-request-detail",
    ),
    path(
        "availability-requests/<int:pk>/<str:decision>/",
        AvailabilityRequestReviewView.as_view(),
        name="availability-request-review",
    ),
    path(
        "staff-calendar/events/",
        StaffScheduleEventsView.as_view(),
        name="staff-calendar-events",
    ),
    path(
        "staff-calendar/api/events/",
        StaffScheduleEventsView.as_view(),
        name="staff-calendar-events-legacy",
    ),
    path("events/", CalendarEventsView.as_view(), name="calendar-events"),
    path("calendar/events/", CalendarEventsView.as_view(), name="calendar-events-legacy"),
    path("move-assignment/", MoveAssignmentView.as_view(), name="move-assignment"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("analytics/report/", AnalyticsReportView.as_view(), name="analytics-report"),
    path("assignments/export-template/", AssignmentTemplateExportView.as_view(), name="assignment-template-export"),
    path("analysis/", AnalyticsReportView.as_view(), name="analysis-report-legacy"),
    path("auto-schedule/preview/", AutoSchedulePreviewView.as_view(), name="auto-schedule-preview"),
    path("auto-schedule/commit/", AutoScheduleCommitView.as_view(), name="auto-schedule-commit"),
    path("auto-generate/", AutoSchedulePreviewView.as_view(), name="auto-generate-legacy"),
    path(
        "auto-generate/commit/",
        AutoScheduleCommitView.as_view(),
        name="auto-generate-commit-legacy",
    ),
    path(
        "approve/",
        LegacyAssignmentBulkActionView.as_view(),
        {"action": "approve"},
        name="approve-assignments-legacy",
    ),
    path(
        "delete-planned/",
        LegacyAssignmentBulkActionView.as_view(),
        {"action": "delete-planned"},
        name="delete-planned-assignments-legacy",
    ),
    path(
        "delete-approved/",
        LegacyAssignmentBulkActionView.as_view(),
        {"action": "delete-approved"},
        name="delete-approved-assignments-legacy",
    ),
    path(
        "delete-filtered/",
        LegacyAssignmentBulkActionView.as_view(),
        {"action": "delete-filtered"},
        name="delete-filtered-assignments-legacy",
    ),
]
