# Generated by Django 5.2.13 on 2026-04-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_holiday_shifttype_is_active_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff_profile', 'date', 'shift_type')},
        ),
    ]
